/**
 * Stable machine-readable error codes. The frontend keys off these strings,
 * so treat them as a public contract — never rename an existing one.
 */
export enum ErrorCode {
  // Auth
  LOGIN_ALREADY_TAKEN = 'LOGIN_ALREADY_TAKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVITE_CODE_REQUIRED = 'INVITE_CODE_REQUIRED',
  INVITE_CODE_INVALID = 'INVITE_CODE_INVALID',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
  CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Phones
  IMEI_ALREADY_EXISTS = 'IMEI_ALREADY_EXISTS',
  PHONE_ALREADY_SOLD = 'PHONE_ALREADY_SOLD',

  // Accessories
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  PRICE_REQUIRED = 'PRICE_REQUIRED',

  // Debts
  DEBT_EXCEEDS_TOTAL = 'DEBT_EXCEEDS_TOTAL',
  DUE_DATE_IN_PAST = 'DUE_DATE_IN_PAST',
  CUSTOMER_REQUIRED_FOR_DEBT = 'CUSTOMER_REQUIRED_FOR_DEBT',
  DEBT_NOT_OPEN = 'DEBT_NOT_OPEN',
  PAYMENT_EXCEEDS_REMAINING = 'PAYMENT_EXCEEDS_REMAINING',

  // Returns
  RETURN_EXCEEDS_SOLD = 'RETURN_EXCEEDS_SOLD',
  RETURN_AMOUNT_EXCEEDS_SOLD = 'RETURN_AMOUNT_EXCEEDS_SOLD',
}
